name: CD - Deploy Model

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train final model
        run: python train.py

      - name: Evaluate final model
        run: python evaluate.py

      - name: Login to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.TOKEN }}
        run: |
          pip install -U "huggingface_hub[cli]"
          huggingface-cli login --token $TOKEN --add-to-git-credential

      - name: Push to HuggingFace Hub
        run: |
          huggingface-cli upload Gatling-D-Ace/Drug-Classification ./App --repo-type=space --commit-message="Sync App files"
          huggingface-cli upload Gatling-D-Ace/Drug-Classification ./Model --repo-type=space --commit-message="Sync Model"
          huggingface-cli upload Gatling-D-Ace/Drug-Classification ./Results --repo-type=space --commit-message="Sync Metrics"